class Races(Enum):
    DWARF = auto()
    ELF = auto()
    HALFLING = auto()
    HUMAN = auto()
    DRAGONBORN = auto()
    GNOME = auto()
    HALFELF = auto()
    HALFORC = auto()
    TIEFLING = auto()